apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dice
  template:
    metadata:
      labels:
        app: dice
    spec:
      containers:
      - name: dice
        image: Dice-Rolling-Stimulator/dice-image:latest
        ports:
        - containerPort: 80
